services:
  immich-optimizer:
    build:
      context: .
      dockerfile: Dockerfile.amd64.goreleaser
    env_file:
      - .env
    volumes:
      - ./watch:/watch
      - ./undone:/undone
    restart: unless-stopped